@baseUrl = http://localhost:3000

GET {{baseUrl}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user",
    "password": ""
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/ad


### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "user",
    "email": "user@user.com.br",
    "password": "123456"
}